### ISSUE TITLE
API Implementaion

### ISSUE THREAD

**Issue by hamza0786** [alexch33/super-video-downloader#1]
Hi can you implement this api instead of youtube-dl-android:
https://ytdlp-api.adaptable.app/api/info?url=https://www.dailymotion.com/video/x87lzbe

it will really decrese the apk size to almost 15-20mbs.also the api completely works as the ytdl-android works.

**Comment by alexch33** [comment]
HI! This application was conceived as an answer to downloaders that use APIs, an application that does all the work on the client, here youtube-dl not only detects, but also downloads. If you want to use API, then you need to implement this by yourself editing VideoService and YoutubeDlDownloaderWorker classes
