### ISSUE TITLE
Add `Material You` or `Monet Icon` support

### ISSUE THREAD

**Issue by vippium** [alexch33/super-video-downloader#14]
It just simple. Just add a material you (monet icon) support for the app. It will match the icon for A12+ Monet users.

**Comment by vippium** [comment]
> no

But why?

**Comment by alexch33** [comment]
> > no
> 
> But why?

why it should be added to project? i don't know, changing icons, colors and e.t.c. so boring, i don't want to do this, if you want, PR are welcome and if result will be good, may it could add to project, but i think this is useless.

**Comment by vippium** [comment]
> if you want, PR are welcome and if result will be good, may it could add to project, but i think this is useless.

I'm going for it. But I haven't found ic_launcher.xml file. All files are named in improper way.

If you can help, let me give ic_launcher.xml file. Or the name of it.

**Comment by vippium** [comment]
I've created a monochrome icon which'll follow the colors. Just import it in the android studio and add the monochrome attribute in <adaptive_icon> with the path of the xml file which'll be generated after importing the monochrome icon.

[superX monochrome.zip](https://github.com/user-attachments/files/20262320/superX.monochrome.zip)

Let me know if it works or not.

**Comment by vippium** [comment]
> why it should be added to project? i don't know, changing icons, colors and e.t.c. so boring, i don't want to do this, if you want, PR are welcome and if result will be good, may it could add to project, but i think this is useless.

I don't think it is useless. Although it is good to have a monochrome icon. Seeing google to introduce material expressive 3, we can also have a monochrome icon for our app too.

After seeing your project/app in detail, I found that you've used a single image for your app icon. not 2 separate files i.e. ic_launcher_foreground and background. You've used the background as black, which is fine. But in foreground, you've used a full image or complete app icon, instead of only logo, excluding the black background.

**Comment by vippium** [comment]
Or if you provide me the full icon png, i'll open a PR. You just have to merge that only.
