### ISSUE TITLE
Fix toast messages while opening app and changing theme

### ISSUE THREAD

**Issue by vippium** [alexch33/super-video-downloader#17]
A permanent toasts are shown while opening the app and changing the theme i.e. light to dark and dark to light mode. These should be disabled while opening the app and toast must be changed to `Changed to Dark mode` or`Changed to Light mode` while changing theme.

Uploading Screenrecording_20241103_171913.mp4…

**Comment by alexch33** [comment]
I don't think toast's text must be `changed to...mode`, but currently toasts has wrong behavior

**Comment by vippium** [comment]
Still Adblock toast pop-ups while changing theme. It's behaviour should be like this: While opening app, it should pop-up. But while changing the theme, it shouldn't.

**Comment by alexch33** [comment]
> Still Adblock toast pop-ups while changing theme. It's behaviour should be like this: While opening app, it should pop-up. But while changing the theme, it shouldn't.

o, fuck, i forgot about adblock toast, i'll fix this in next update ;-)
