### ISSUE TITLE
The download speed is too slow, increasing the number of threads is useless

### ISSUE THREAD

**Issue by nizhiyi** [alexch33/super-video-downloader#2]

**Comment by alexch33** [comment]
i don't know what exactly downloader you are using. Numbers of thresads working only for M3U8/MPD formats. For regular file downloading exists constant THREAD_COUNT in CustomRegularDownloaderWorker, you could try change, but there is 3th situation, when regular file downloading by youtubedl(if detected by link) and 4th situation, when download speed limited by server

**Comment by alexch33** [comment]
@nizhiyi i have pushed branch "develop" (you can did check help or not), in develop brunch added setting of regular downloader's threads count
