### ISSUE TITLE
Please add veeps support

### ISSUE THREAD

**Issue by notsaten** [alexch33/super-video-downloader#25]
I tried downloading a veeps concert and at first the website didn't load but after turning my vpn off (I use a USA server to get veeps all access) it loaded fine, but when i try to play a video i get this
![Screenshot_20241126-000524](https://github.com/user-attachments/assets/b95cd9d4-8ec5-4190-90d0-41c40e5a011a)

**Comment by alexch33** [comment]
> I tried downloading a veeps concert and at first the website didn't load but after turning my vpn off (I use a USA server to get veeps all access) it loaded fine, but when i try to play a video i get this ![Screenshot_20241126-000524](https://private-user-images.githubusercontent.com/189678714/389741141-b95cd9d4-8ec5-4190-90d0-41c40e5a011a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTQxNDIsIm5iZiI6MTczMjYxMzg0MiwicGF0aCI6Ii8xODk2Nzg3MTQvMzg5NzQxMTQxLWI5NWNkOWQ0LThlYzUtNDE5MC05MGQwLTQxYzQwZTVhMDExYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwOTM3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDdiYzM3NGQ0YzVhYjRlYjA4YTlkNzg2MTAyNzAyNjQ5MmUxOWJmODBlODQzMDM0ZGRjZTJhYzU2ZWZmZjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hOWSJMSZwkTmka9vkUkl1lqT6bR0X54OVYaDCqiO4c8)

Hi, I'd successfully download from [live](https://veeps.com/live), and mp4 from home page, should i have US IP address for getting access to this [concert](https://veeps.com/falloutboy/abcd8fc5-311a-44df-b075-a822a866f237)  for example? I've see button ticket for 14,7:) or may be some videos will be available after sign up? Could you provide additional info about how to reproduce issue? And what is your android version?

**Comment by alexch33** [comment]
Also you can try to use desktop mode and turns off check boxes about video detections from settings this decreased count of requests, videos not detecting too?

**Comment by alexch33** [comment]
there was time to respond, i am closing the issue
