### ISSUE TITLE
Why it's not working below api 30 is there any specific reason to set compile sdk 29

### ISSUE THREAD

**Issue by nabeelabiddev** [alexch33/super-video-downloader#37]
I used this code in my project in release build below 30 it's not working in debug is working on all versions

**Comment by alexch33** [comment]
I had faced similar issue, youtube-dl did not work in realease with
shrinkResources minifyEnabled options, setting this options to false
resolved problem, also with some gradle versions may not work too, try to
change if workaround above not working


пн, 16 дек. 2024 г., 20:06 Nabeel Abid ***@***.***>:

**Comment by alexch33** [comment]
@nabeelabiddev, just for research, could you try build from [api_24_support](https://github.com/alexch33/super-video-downloader/tree/api_24_support) and tell is issue present?

**Comment by harisEshaafi** [comment]
ok i  am working on it actualy i am using dynamic module for my release build so cannot use all your code i have implemented specific changes   i have seen your commit and i already done changes like BASe64 types but not working although i will try your code and tell you once done

**Comment by alexch33** [comment]
i've tested on API 24 and 27 emulator and youtubedl working and mp4 downloader working too (in release mode) it should work, last changes already merged and available in version 0.3.0

**Comment by alexch33** [comment]
api 24 support added, and tested, downloaders are working, i am closing the issue
