### ISSUE TITLE
Video download successfully but without audio 

### ISSUE THREAD

**Issue by MuhammadAsad786** [alexch33/super-video-downloader#43]
I download the video from instagram , and its download successfully. but when i play the video on player then audio file does not merge with video file

**Comment by alexch33** [comment]
i have tried download from instagram and 1280P and 640P has no sound, but 1333P - has, also MP4 files detected on instagram has sound, you could try 1333P or MP4 for now, than i will try investigate this issue

**Comment by alexch33** [comment]
@MuhammadAsad786  i have found problem, already fixed, new apk version will be downloaded and few minutes, thanks you for your feedback, this helped a lot!

**Comment by alexch33** [comment]
this was error in new refactored code, i replaced `+bestaudio*` to `+bestaudio`, this fixed the issue, i am closing
